image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - java -jar ./src/test/resources/webdrivermanager-4.0.0-fat.jar

build_script:
  - chmod +x gradlew
  - ./gradlew test --info